### ISSUE TITLE
./honsshctrl.sh start poroblem

### ISSUE THREAD

**Issue by tfalvi** [tnich/honssh#128]
Hi there, I'm working on a Uni project where I have HonSSH sitting between the attacker and 4 honeypots which are managed with Puppet Enterprise for future further deploymmments.

at the moment I just finished configuring the honeypots and I was configuring honssh.cfg to get it ready to start, once i hit

`./honsshctrl.sh start` 

I get this error:

> root@honssh:/opt/honssh# ./honsshctrl.sh start
honsshctrl.sh[19726]: Starting honssh in background...
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 674, in run
    runApp(config)
  File "/usr/local/lib/python2.7/dist-packages/twisted/scripts/twistd.py", line 25, in runApp
    runner.run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 381, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 453, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/app.py", line 464, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/lib/python2.7/dist-packages/twisted/application/service.py", line 416, in loadApplication
    application = sob.loadValueFromFile(filename, 'application')
  File "/usr/local/lib/python2.7/dist-packages/twisted/persisted/sob.py", line 177, in loadValueFromFile
    eval(codeObj, d, d)
  File "honssh.tac", line 39, in <module>
    from honssh.config import Config
exceptions.ImportError: No module named honssh.config
Failed to load application: No module named honssh.config

Is that something to do with dependencies or have I missed anything on the .cfg file?

**Comment by tnich** [comment]
Hey,
This might help, https://github.com/tnich/honssh/issues/113
Let me know if you still have issues after trying the things in that thread. I'll try and look into why it's happening at some point :)

**Comment by tfalvi** [comment]
Thank you very much for that, I will let you know once I start up my
machine in the morning, if I need some help I might contact you if that's
ok 😅

Cheers,
Alvi

**Comment by tfalvi** [comment]
Yeah I managed to fix it. Now HonSSH is starting, thank you.

Do you think you could help me out finishing my setup or showing me how I test everything is working. I'm pretty new to linux and I would love some assistance. happy to host a teamviewer session or something. (let me know if you need a private contact)

Thanks in advance, you can probably close this thread.

**Comment by tnich** [comment]
Glad its fixed and happy to help , just email me in the address found in the code.
