### ISSUE TITLE
HonsshServerFactory instance has no attribute 'ourVersionString'

### ISSUE THREAD

**Issue by katkad** [tnich/honssh#63]
hello, what version of twisted do you use?

I got 13.2.0 and honssh doesn't work at all. I got:

2015-10-11 07:07:33+0200 [honssh.server.HonsshServerFactory] Unhandled Error

        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 73, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
            return func(*args,**kw)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
            why = selectable.doRead()
        --- <exception caught here> ---
          File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 1063, in doRead
            protocol = self.factory.buildProtocol(self._buildAddr(addr))
          File "/opt/honssh/honssh/server.py", line 185, in buildProtocol
            t.ourVersionString = self.ourVersionString
        exceptions.AttributeError: HonsshServerFactory instance has no attribute 'ourVersionString'

when I delete line
t.ourVersionString = self.ourVersionString
from server.py

it works okay. I found out t.ourVersionString is already set, and there's nothing in self.ourVersionString .

**Comment by tnich** [comment]
Hi,

Sorry for the slow reply.

I have been using a few different versions including 13.2.0 and the newer 15.4.0 - both are fine.

It looks like the self.ourVersionString variable is not being set. This variable should be set when HonSSH first boots up. It connects to the honeypot and acquires their version string to use.

Do you know if HonSSH had an issue connecting to the honeypot when it was first started?

Many thanks,
Tom

**Comment by katkad** [comment]
hello, thank you for the reply.

I think I didn't set up routing and forwarding yet, and that's why it didn't work.

TY for answer :) Working fine now. I'm closing the issue.
